### ISSUE TITLE
Error: Cannot find module 'yargs'

### ISSUE THREAD

**Issue by skynet** [whatwedo/gulp-wp-theme#46]
```
Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/wordpress/wp-content/themes/gulp-wp-theme/gulp/config.js:14:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by renestalder** [comment]
Did you check the node_modules folder if there is a yargs folder? Is it in your package.json?

**Comment by renestalder** [comment]
I close here without further information provided.
